version: '3'
services:
  furthrmind-server:
    image: 'docker.io/furthrresearch/furthrmind-server-v1:latest'
    restart: unless-stopped
    depends_on:
      - db
    environment:
      MONGODB_URI: mongodb://db:27017
      MONGODB_DB: FURTHRmind
      DEFAULT_ADMIN: ""
      ROOT_URL: "https://furthrmind.furthr-research.com" # change
      GUNICORN_CMD_ARGS: -b 0.0.0.0:8080 -w 3
      S3_BUCKET: furthrmind
      S3_KEY: "NicNlFvpC5WLmk1gs269" # change
      S3_SECRET: "AJukahGO46BwICA7SZZk" # change
      S3_REGION: 'local'
      S3_ENDPOINT: 'https://files.furthrmind.furthr-research.com:9000'
      WEBDATACALC_API_KEY: placeholder # change
      WEBDATACALC_API: 'http://dockerrun:8088'
    ports:
      - 127.0.0.1:8080:8080
  #    networks:
  #      - backend
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300
  db:
    image: mongo
    restart: unless-stopped
    ports:
      - 127.0.0.1:27017:27017
    logging:
      driver: "none"
    environment:
      MONGO_INITDB_DATABASE: FURTHRmind
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /data/log
    volumes:
      - mongodb-data:/data/db
      - mongodb-log:/data/log
  #    networks:
  #      - backend
  minio:
    image: minio/minio
    entrypoint: sh
    command: -c 'mkdir -p /export/furthrmind && /usr/bin/docker-entrypoint.sh minio
      server /export'
    ports:
      - 127.0.0.1:9000:9000
    volumes:
      - minio-data:/export
    environment:
      MINIO_ACCESS_KEY: "NicNlFvpC5WLmk1gs269" # change
      MINIO_SECRET_KEY: "AJukahGO46BwICA7SZZk" # change
      MINIO_REGION_NAME: 'local'
    # networks:
    #   - backend
  coderunner:
    image: furthrresearch/coderunner
    build: ./WebDataCalc/CodeRunner
    profiles:
      - donotrun
  dockerrun:
    image: glot/docker-run
    restart: unless-stopped
    ports:
      - 127.0.0.1:8088:8088
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      API_ACCESS_TOKEN: placeholder # change
      DOCKER_CONTAINER_NETWORK_DISABLED: 'false'

volumes:
  mongodb-data:
    driver: local
  mongodb-log:
    driver: local
  minio-data:
    driver: local

#networks:
#  backend:
#    driver: bridge
