version: '3'
services:
  furthrmind-server:
    image: 'docker.io/furthrresearch/furthrmind-server-v1:latest'
    restart: unless-stopped
    environment:
      MONGODB_URI: mongodb://localhost:27017
      MONGODB_DB: FURTHRmind
      DEFAULT_ADMIN: ""
      ROOT_URL: "http://localhost"
      GUNICORN_CMD_ARGS: -b 127.0.0.1:8080 -w 3
    network_mode: host
  furthrmind-TSR:
    image: 'docker.io/furthrresearch/furthrmind-server-v1:latest'
    restart: unless-stopped
    environment:
      TSR_ENABLED: false
      TSR_CERT: ""
      TSR_URL: ""
    command: sh ./startTSR.sh

  #    ports:
  #      - 8080:8080
  #    extra_hosts:
  #      - host.docker.internal:host-gateway
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300
