version: '3'
services:
  furthrmind-server:
    image: 'docker.io/furthrresearch/furthrmind-server-v1:latest'
    restart: unless-stopped
    environment:
      MONGODB_URI: mongodb://localhost:27017
      MONGODB_DB: FURTHRmind
      DEFAULT_ADMIN: ""
      ROOT_URL: "http://localhost"
      GUNICORN_CMD_ARGS: -b 127.0.0.1:8080 -w 3
    network_mode: host

  furthrmind-TSR:
    image: 'docker.io/furthrresearch/furthrmind-time-server-v1:latest'
    restart: unless-stopped
    environment:
      TSR_ENABLED: "false"
      TSR_CERT: ""
      TSR_URL: ""
      MONGODB_URI: mongodb://localhost:27017
      MONGODB_DB: FURTHRmind
    volumes:
      - /opt/tsa_cert:/tsa_cert

  coderunner:
    image: furthrresearch/coderunner
    build: ./WebDataCalc/CodeRunner
    profiles:
      - donotrun
  dockerrun:
    image: glot/docker-run
    restart: unless-stopped
    ports:
      - 127.0.0.1:8088:8088
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      API_ACCESS_TOKEN: placeholder # change
      DOCKER_CONTAINER_NETWORK_DISABLED: 'false'

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300
