version: '3'
services:
  furthrmind-server:
    image: 'docker.io/furthrresearch/furthrmind-server-v1:latest'
    restart: unless-stopped
    environment:
      MONGODB_URI: mongodb://localhost:27017
#      MONGODB_URI: mongodb://host.docker.internal:27017
      MONGODB_DB: FURTHRmind
      DEFAULT_ADMIN: "demo@furthr-research.com"
      ROOT_URL: "http://localhost"
      GUNICORN_CMD_ARGS: -b 127.0.0.1:8080 -w 3
    network_mode: host
#    ports:
#      - 8080:8080
#    extra_hosts:
#      - host.docker.internal:host-gateway
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    command: --interval 300