version: '3'
services:
  furthrmind-server:
    image: 'docker.io/furthrresearch/furthrmind-server-v1:latest'
    restart: unless-stopped
    depends_on:
        - db
    environment:
      MONGODB_URI: mongodb://db:27017
      MONGODB_DB: FURTHRmind
      DEFAULT_ADMIN: "demo@furthr-research.com"
      GUNICORN_CMD_ARGS: -b 127.0.0.1:8080 -w 3
    ports:
      - 8080:8080
#    networks:
#      - backend
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    command: --interval 300
  db:
    image: mongo
    restart: unless-stopped
    ports:
      - 127.0.0.1:27017:27017
    logging:
      driver: "none"
    environment:
      MONGO_INITDB_DATABASE: FURTHRmind
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodb-data:/data/db
#    networks:
#      - backend

volumes:
  mongodb-data:
    driver: local

#networks:
#  backend:
#    driver: bridge