version: '3'
services:
  furthrmind-server:
    image: 'docker.io/furthrresearch/furthrmind-server-v1:latest'
    restart: unless-stopped
    depends_on:
      - db
    environment:
      MONGODB_URI: mongodb://db:27017
      MONGODB_DB: FURTHRmind
      DEFAULT_ADMIN: ""
      ROOT_URL: "http://localhost"
      GUNICORN_CMD_ARGS: -b 0.0.0.0:8080 -w 3
    ports:
      - 127.0.0.1:8080:8080

  furthrmind-TSR:
    image: 'docker.io/furthrresearch/furthrmind-time-server-v1:latest'
    restart: unless-stopped
    environment:
      TSR_ENABLED: "false"
      TSR_CERT: ""
      TSR_URL: ""
      MONGODB_URI: mongodb://localhost:27017
      MONGODB_DB: FURTHRmind
    volumes:
      - /opt/tsa_cert:/tsa_cert

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300

  db:
    image: mongo
    restart: unless-stopped
    ports:
      - 127.0.0.1:27017:27017
    logging:
      driver: "none"
    environment:
      MONGO_INITDB_DATABASE: FURTHRmind
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /data/log
    volumes:
      - mongodb-data:/data/db
      - mongodb-log:/data/log

  coderunner:
    image: furthrresearch/coderunner
    build: ./WebDataCalc/CodeRunner
    profiles:
      - donotrun

  dockerrun:
    image: glot/docker-run
    restart: unless-stopped
    ports:
      - 127.0.0.1:8088:8088
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      API_ACCESS_TOKEN: placeholder # change
      DOCKER_CONTAINER_NETWORK_DISABLED: 'false'

volumes:
  mongodb-data:
    driver: local
  mongodb-log:
    driver: local

